project:
  type: website

website:
  title: "toothless-candy-bucket"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: materials.qmd
        text: Materials
      - href: electrical.qmd
        text: Electrical Design
      - href: mechanical.qmd
        text: Mechanical Design
      - href: testbenches.qmd
        text: Testbenches
      - href: references.qmd
        text: References
      - href: members.qmd
        text: People

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



