project:
  type: website

website:
  title: "Toothless Candy Bucket"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-heart-fill
      - href: materials.qmd
        text: Materials
        icon: cart-check-fill
      - href: electrical.qmd
        text: Electrical Design
        icon: cpu-fill
      - href: mechanical.qmd
        text: Mechanical Design
        icon: wrench-adjustable
      - href: software.qmd
        text: Software Design
        icon: code-slash
      - href: testbenches.qmd
        text: Testbenches
        icon: pen-fill
      - href: future.qmd
        text: Future Work
        icon: arrow-repeat
      - href: references.qmd
        text: References
        icon: link-45deg
      - href: members.qmd
        text: People
        icon: people-fill

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    math:
      method: mathjax
      options:
        autoNumber: "AMS"
      citations: true
    link-external-icon: true
    code-line-numbers: true





