project:
  type: website

website:
  title: "toothless-candy-bucket"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-heart-fill
      - href: materials.qmd
        text: Materials
      - href: electrical.qmd
        text: Electrical Design
      - href: mechanical.qmd
        text: Mechanical Design
      - href: software.qmd
        text: Software Design
      - href: testbenches.qmd
        text: Testbenches
        icon: pen-fill
      - href: future.qmd
        text: Future Work
      - href: references.qmd
        text: References
      - href: members.qmd
        text: People
        icon: people-fill

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    math:
      method: mathjax
      options:
        autoNumber: "AMS"
      citations: true
    link-external-icon: true
    code-line-numbers: true





